options:
  replica_set_name:
    type: string
    description: Name of the replica set
    default: rs0
  standalone:
    type: boolean
    description: |
      Indicates if it is an standalone cluster or not.

      If True, replica set will be disabled.
      If False, replica set will be enabled.
    default: false